# Generated by Django 2.1.4 on 2018-12-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendaTelefonica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
    ]
