# Generated by Django 2.1.4 on 2018-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendaTelefonica', '0002_remove_persona_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
